# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oo9Kdd9Bc0naqxsIC_Mn-Qz2uCZFBu6d
"""

import matplotlib.pyplot as plt

# 1. Solicite ao usuário:
#- Valor inicial do investimento (float)
#- Taxa de juros anual em % (float)
#- Prazo do investimento em anos (int)

valor_investimento = float(input("Digite o valor do investimento inicial: R$ "))
taxa_juros_anual = float(input("Digite a taxa de juros anual (%): "))
prazo = int(input("Digite o prazo em anos: "))
aporte = float(input("Digite o valor do aporte mensal: R$ "))

#2. Converta a taxa anual em mensal.
taxa_juros_mensal = (1 + taxa_juros_anual/100) ** (1/12) - 1

#3. Calcule e armazene o saldo de cada mês usando juros compostos, guardando os resultados em uma lista.
saldos = []
saldo = valor_investimento
total_meses = prazo * 12

for mes in range(1, total_meses + 1):
    saldo = saldo * (1 + taxa_juros_mensal) + aporte  # juros compostos + aporte
    saldos.append(saldo)

print(f"\nSaldo final após {prazo} anos: R$ {saldos[-1]:.2f}\n")
print("Evolução mês a mês:")
for i, valor in enumerate(saldos, start=1):
    print(f"Mês {i}: R$ {valor:.2f}")

# 5. 4- Ao final:
#- Imprima o saldo final formatado com R$ e duas casas decimais.
#- Imprima a evolução mês a mês (linha a linha).
#- Gere um gráfico de linha mostrando o crescimento do saldo no tempo
plt.plot(range(1, total_meses + 1), saldos, marker='o')
plt.title("Evolução do Investimento")
plt.xlabel("Mês")
plt.ylabel("Saldo (R$)")
plt.grid(True)
plt.show()

