# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sODiPelSt1B4QxWp03u_r_wJunMJmndR
"""

# Quiz - Skyra

#Problema: Calcular 10% de desconto em uma compra

#Enunciado:
#Peça ao usuário o valor da compra.
#Calcule e mostre o valor final com 10% de desconto fixo.

valor = float(input("Qual é o valor da sua compra?"))
print(valor)

valorcomdesconto = valor * 0.9
print("O valor da sua compra com 10% de desconto é {} reais" . format(valorcomdesconto))
