# -*- coding: utf-8 -*-
"""Skyra_carteiradeinvestimentos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUUahHYBsMXf7p8OSmb3SFomt14pIJ1B
"""

"""
Vamos exercitar: Hoje vamos construir um simulador de carteira de investimentos.

Você poderá cadastrar ativos e valores investidos, e ver ao final ver o resumo do seu portfólio.

Passos:

Criar 2 listas de ativos e valores
Cadastrar ativos e valores (while)
Exibir o total investido (sum)
Calcular o percentual de cada ativo (/, *)
Identificar ativos com mais de 50% da carteira para entender riscos (if,else)
Calcular o valor médio investido por ativo (sum/len)

"""

# Criar 2 listas de ativos e valores
ativos = ["msbr3", "vale3", "petra4"]
valores = [1, 2, 3]

# Cadastrar ativos e valores (while)
ativos = []
valores = []
nome_ativos = ""
while nome_ativos != "fim":
  nome_ativos = input("Digite o nome do ativo: \n")
  if (nome_ativos != "fim"):
    ativos.append(nome_ativos)
print (ativos)

valor_ativos = ""
while valor_ativos != "fim":
  valor_ativos = input("Digite o valor do ativo: \n")
  if (valor_ativos != "fim"):
    valores.append(int(valor_ativos))
print (valores)

# Exibir o total investido (sum)

soma = sum(valores)
print(soma)

# Calcular o percentual de cada ativo
# Identificar ativos com mais de 50% da carteira para entender riscos

for i in range(len(ativos)):
  percentual = valores[i] / soma * 100
  print(f"{ativos[i]}: {percentual:.2f}%")
  if percentual >= 50:
    print("Risco Alto")
  else:
    print("Risco Baixo")

# percentual_ativos = valores[0] / soma * 100
# print (f"{percentual_ativos:.2f}")

# Cálculo da média

media = sum(valores) / len(valores)
print(media)

