# -*- coding: utf-8 -*-
"""Cadastro_Analise_de_Compras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ctYstk3G1zmCFsD9lUB3T201-LkuzgN
"""

#Cadastro e Análise de Compras

#Você está construindo um sistema simples para registrar compras de uma pessoa.

#O programa deve permitir digitar o nome do produto e o valor da compra (quantas vezes quiser).
#Ao final, ele deve:
#Mostrar todos os produtos e valores cadastrados
#Calcular o total gasto
#Calcular a média de gasto por item
#Alertar se algum item custou mais de R$ 100 (valor considerado alto)


produtos = []
valores = []

while True:
    nome = input("Digite o nome do produto (digite 'fim' para terminar): ")
    if nome.lower() == 'fim':
        break
    valor = float(input("Digite o valor do produto: R$ "))

    produtos.append(nome)
    valores.append(valor)

print("Produtos cadastrados:")
for i in range(len(produtos)):
  print(f"{produtos[i]} - R$ {valores[i]:.2f}")

total = sum(valores)
media = total / len(valores) if len(valores) > 0 else 0

print(f"Total gasto: R$ {total:.2f}")
print(f"Média de gasto por item: R$ {media:.2f}")

for i in range(len(valores)):
  if valores[i] > 100:
    print(f"O item {produtos[i]} custou mais de R$ 100.")